server:
  port: ${CUSTOMER_SERVICE_PORT:8081}

spring:
  application:
    name: customer-service
  datasource:
    url: ${CUSTOMER_DB_URL:jdbc:h2:mem:customerdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1}
    username: ${CUSTOMER_DB_USERNAME:sa}
    password: ${CUSTOMER_DB_PASSWORD:}
    driver-class-name: ${CUSTOMER_DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:https://login.microsoftonline.com/94b15b07-9bad-4661-8554-aad0e62b18de/v2.0}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
  security:
    audiences: ${JWT_AUDIENCES:api://0f18b5b0-285b-4050-a959-245884ab7670,0f18b5b0-285b-4050-a959-245884ab7670}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
